# Generated by Django 2.1.15 on 2019-12-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('idd', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='IDD')),
            ],
        ),
    ]
